workflows:
  ios-release:
    name: iOS Release Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      groups:
        - signing_credentials
    scripts:
      - name: Decode signing files
        script: |
          echo $CERTIFICATE_BASE64 | base64 --decode > certificate.p12
          echo $PROVISIONING_PROFILE_BASE64 | base64 --decode > provisioning_profile.mobileprovision
      - name: Set up keychain and provisioning
        script: |
          keychain initialize
          keychain add-certificates --p12 certificate.p12 --password $CERTIFICATE_PASSWORD
          xcode-project use-profiles --profile provisioning_profile.mobileprovision
      - name: Install Flutter dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace $XCODE_WORKSPACE \
                     -scheme $XCODE_SCHEME \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive archive
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios_out
    artifacts:
      - build/ios_out/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_ID
        submit_to_testflight: true